### PR TITLE
Add Serde to LdapFilter

### PR DESCRIPTION
**Pull request by Firstyear**
This allows using LdapFilter in config and other serde contexts.

### CODE REVIEW

**Review by nitnelave — APPROVED** [review]
Maybe add a test that checks that serializing and deserializing gives the initial structure? That way it's easy to add lots of examples, including more complex ones

**Comment by Firstyear** [comment]
@nitnelave At the moment I'm only interesting in the deserialising direction, not the reverse. But if I added serialisiation I would certainly add the reflexive tests. 

Do you think there is a need for serialising?

**Comment by nitnelave** [comment]
It would simply make for easy tests :)

**Comment by Firstyear** [comment]
> It would simply make for easy tests :)

I think because we only target deserialisation at the moment, and we are using the peg parser that already has a lot of tests I'm pretty happy this is well covered :)

**Pull request merged**
